services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ecommerce
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      TZ: America/Bogota
    networks:
      app-network:
        ipv4_address: 172.27.0.4
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/conf:/etc/mysql/conf.d


volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
