services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=${PASSWORD}
      - ACCEPT_EULA=Y
    networks:
      app-network:
        ipv4_address: 172.27.0.4
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "${PASSWORD}", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 20s
      retries: 5
volumes:
  sqlserver_data:
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16