server:
  port: 8080

spring:
  application:
    name: ecommerce
  data:
    mongodb:
      uri: mongodb://mongo:27017/ecommerce
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  messages:
    basename: i18n.messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    jwt:
      key:
        private: ${JWT_PRIVATE_KEY}
      user:
        generator: ${JWT_GENERATOR_USER}
stripe:
  api:
    key: ${STRIPE_API_KEY}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs
file:
  upload-dir: upload/images
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
